### ISSUE TITLE
--limit not working

### ISSUE THREAD

**Issue by vapniks** [commonism/iptables-trace#2]
I get the following error when I use the `--limit` argument:
```
> iptables-trace --limit --destination 192.168.0.1 -p tcp

Namespace(bpf=None, chain=['OUTPUT', 'PREROUTING'], clear_chain=False, destination='192.168.0.1', limit=True, protocol='tcp', source=None, xmark_mask='0x800001ff')
Traceback (most recent call last):
  File "/home/me/iptables-trace.py", line 283, in <module>
    main()
  File "/home/me/iptables-trace.py", line 247, in main
    chain.append_rule(mark)
  File "/usr/local/lib/python2.7/dist-packages/iptc/ip4tc.py", line 1424, in append_rule
    rule.final_check()
  File "/usr/local/lib/python2.7/dist-packages/iptc/ip4tc.py", line 953, in final_check
    match.final_check()
  File "/usr/local/lib/python2.7/dist-packages/iptc/ip4tc.py", line 335, in final_check
    self._update_parameters()
  File "/usr/local/lib/python2.7/dist-packages/iptc/ip4tc.py", line 439, in _update_parameters
    self.set_parameter(k, v)
  File "/usr/local/lib/python2.7/dist-packages/iptc/ip4tc.py", line 281, in set_parameter
    return self.parse(parameter.replace("_", "-"), value)
  File "/usr/local/lib/python2.7/dist-packages/iptc/ip4tc.py", line 328, in parse
    self._parse(argv, inv, entry)
  File "/usr/local/lib/python2.7/dist-packages/iptc/ip4tc.py", line 596, in _parse
    self._orig_parse, self._orig_options)
  File "/usr/local/lib/python2.7/dist-packages/iptc/xtables.py", line 748, in new
    return fn(*args)
  File "/usr/local/lib/python2.7/dist-packages/iptc/xtables.py", line 1032, in parse_match
    argv[0]))
iptc.xtables.XTablesError: limit: no such parameter limit limit-burst
```

**Comment by commonism** [comment]
Your iptables version must be rather old?
In that case - nothing I could fix.

**Comment by vapniks** [comment]
iptables v1.4.21

**Comment by commonism** [comment]
fixed in https://github.com/commonism/iptables-trace/commit/2c7b331b04e9f4daa5b0ec30fad62c6c1b138dc0
