### ISSUE TITLE
Segmentation fault on Debian 9 (python 2.7)

### ISSUE THREAD

**Issue by deric** [commonism/iptables-trace#4]
Simply running `python iptables-trace.py` causes segmentation fault. Here's `gdb` output:
```
(gdb) file python
Reading symbols from python...(no debugging symbols found)...done.
(gdb) run iptables-trace.py
Starting program: /usr/bin/python iptables-trace.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Namespace(bpf=None, chain=['OUTPUT', 'PREROUTING'], clear_chain=False, destination=None, limit=False, protocol=None, source=None, xmark_mask='0x800001ff')

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff51a60c9 in nlif_query () from /usr/lib/x86_64-linux-gnu/libnfnetlink.so.0
```
backtrace:
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff51a60c9 in nlif_query () from /usr/lib/x86_64-linux-gnu/libnfnetlink.so.0
(gdb) backtrace
#0  0x00007ffff51a60c9 in nlif_query () from /usr/lib/x86_64-linux-gnu/libnfnetlink.so.0
#1  0x00007ffff5fd6038 in ffi_call_unix64 () from /usr/lib/x86_64-linux-gnu/libffi.so.6
#2  0x00007ffff5fd5a9a in ffi_call () from /usr/lib/x86_64-linux-gnu/libffi.so.6
#3  0x00007ffff61ea224 in _call_function_pointer (argcount=1, resmem=0x7fffffffc7c0, restype=<optimized out>, atypes=0x7fffffffc780, 
    avalues=0x7fffffffc7a0, pProc=0x7ffff51a60c0 <nlif_query>, flags=4353) at ./Modules/_ctypes/callproc.c:841
#4  _ctypes_callproc () at ./Modules/_ctypes/callproc.c:1184
#5  0x00007ffff61e9be5 in PyCFuncPtr_call.lto_priv.56 () at ./Modules/_ctypes/_ctypes.c:3979
#6  0x000055555563c0c3 in PyObject_Call () at ../Objects/abstract.c:2547
#7  0x000055555565535f in do_call (nk=<optimized out>, na=1, pp_stack=0x7fffffffca88, 
    func=<_FuncPtr(__name__='nlif_query') at remote 0x7ffff53d1ae0>) at ../Python/ceval.c:4569
#8  call_function (oparg=<optimized out>, pp_stack=0x7fffffffca88) at ../Python/ceval.c:4374
#9  PyEval_EvalFrameEx () at ../Python/ceval.c:2989
#10 0x000055555565514f in fast_function (nk=<optimized out>, na=<optimized out>, n=<optimized out>, pp_stack=0x7fffffffcbd8, 
    func=<function at remote 0x7ffff53c0140>) at ../Python/ceval.c:4437
#11 call_function (oparg=<optimized out>, pp_stack=0x7fffffffcbd8) at ../Python/ceval.c:4372
#12 PyEval_EvalFrameEx () at ../Python/ceval.c:2989
#13 0x000055555565514f in fast_function (nk=<optimized out>, na=<optimized out>, n=<optimized out>, pp_stack=0x7fffffffcd28, 
    func=<function at remote 0x7ffff53c00c8>) at ../Python/ceval.c:4437
#14 call_function (oparg=<optimized out>, pp_stack=0x7fffffffcd28) at ../Python/ceval.c:4372
#15 PyEval_EvalFrameEx () at ../Python/ceval.c:2989
#16 0x000055555564d9f5 in PyEval_EvalCodeEx () at ../Python/ceval.c:3584
#17 0x000055555566a5be in function_call.lto_priv () at ../Objects/funcobject.c:523
#18 0x000055555563c0c3 in PyObject_Call () at ../Objects/abstract.c:2547
#19 0x000055555563bd34 in call_function_tail (args=(<nflog_data at remote 0x7ffff4f360e0>,), callable=<function at remote 0x7ffff53c0d70>)
    at ../Objects/abstract.c:2579
#20 PyObject_CallFunction () at ../Objects/abstract.c:2603
#21 0x000055555563b55c in _PyObject_GenericGetAttrWithDict () at ../Objects/object.c:1399
#22 0x000055555564f67a in PyEval_EvalFrameEx () at ../Python/ceval.c:2543
#23 0x000055555565514f in fast_function (nk=<optimized out>, na=<optimized out>, n=<optimized out>, pp_stack=0x7fffffffd278, 
    func=<function at remote 0x7ffff53d6668>) at ../Python/ceval.c:4437
#24 call_function (oparg=<optimized out>, pp_stack=0x7fffffffd278) at ../Python/ceval.c:4372
#25 PyEval_EvalFrameEx () at ../Python/ceval.c:2989
#26 0x000055555564d9f5 in PyEval_EvalCodeEx () at ../Python/ceval.c:3584
#27 0x000055555566a5be in function_call.lto_priv () at ../Objects/funcobject.c:523
#28 0x000055555563c0c3 in PyObject_Call () at ../Objects/abstract.c:2547
#29 0x0000555555659a10 in PyEval_CallObjectWithKeywords () at ../Python/ceval.c:4221
#30 0x00007ffff61ef7e0 in _CallPythonObject (pArgs=<optimized out>, flags=257, 
    converters=(<_ctypes.PyCPointerType at remote 0x555555cf7ea0>, <_ctypes.PyCSimpleType at remote 0x555555c3cea0>, <_ctypes.PyCPointerType at remote 0x555555ce8d00>, <_ctypes.PyCSimpleType at remote 0x555555c3cea0>), callable=<function at remote 0x7ffff4f81230>,
```

`libnfnetlink0` version `1.0.1-3`

**Comment by deric** [comment]
more readable trace:
```
Current thread 0x00007f5eae1e5700 (most recent call first):
  File "/usr/lib/python3/dist-packages/libnetfilter/netlink/__init__.py", line 34 in query
  File "/usr/lib/python3/dist-packages/libnetfilter/netlink/__init__.py", line 28 in resolve
  File "/usr/lib/python3/dist-packages/libnetfilter/log/__init__.py", line 127 in outdev
  File "iptables-trace.py", line 139 in trace_cb
  File "/usr/lib/python3/dist-packages/libnetfilter/log/__init__.py", line 82 in _cb
  File "/usr/lib/python3/dist-packages/libnetfilter/log/__init__.py", line 52 in handle_packet
  File "/usr/lib/python3/dist-packages/libnetfilter/log/__init__.py", line 56 in handle_io
  File "iptables-trace.py", line 280 in main
  File "iptables-trace.py", line 288 in <module>
```

**Comment by commonism** [comment]
Hi,

I can report it works fine on buster, even with python3 and python3-iptables from apt.

I guess your problem was resolved in https://github.com/commonism/python-libnetfilter/commit/816c22e810f9b09069e8d1b75df20f6983f237d3#diff-c936f00bafa22f8d0dc0e6dba5bffc98L35
in 2017 already and now it was pushed.
